#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// gMapGroup_UnusedEmeraldTowns

// gMapGroup_UnusedEmeraldDungeons

// gMapGroup_UnusedEmeraldInteriors1
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F    (0 | (2 << 8))
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F    (1 | (2 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F        (2 | (2 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F        (3 | (2 << 8))
#define MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB (4 | (2 << 8))

// gMapGroup_UnusedEmeraldInteriors2
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F (0 | (3 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F (1 | (3 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY      (2 | (3 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_HALL       (3 | (3 << 8))

// gMapGroup_UnusedEmeraldSpecialArea
#define MAP_SOUTHERN_ISLAND_EXTERIOR (0 | (4 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR (1 | (4 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR    (2 | (4 << 8))
#define MAP_BIRTH_ISLAND_HARBOR      (3 | (4 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR      (4 | (4 << 8))
#define MAP_NAVEL_ROCK_HARBOR        (5 | (4 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE      (6 | (4 << 8))
#define MAP_NAVEL_ROCK_B1F           (7 | (4 << 8))
#define MAP_NAVEL_ROCK_FORK          (8 | (4 << 8))
#define MAP_NAVEL_ROCK_UP1           (9 | (4 << 8))
#define MAP_NAVEL_ROCK_UP2           (10 | (4 << 8))
#define MAP_NAVEL_ROCK_UP3           (11 | (4 << 8))
#define MAP_NAVEL_ROCK_UP4           (12 | (4 << 8))
#define MAP_NAVEL_ROCK_TOP           (13 | (4 << 8))
#define MAP_NAVEL_ROCK_DOWN01        (14 | (4 << 8))
#define MAP_NAVEL_ROCK_DOWN02        (15 | (4 << 8))
#define MAP_NAVEL_ROCK_DOWN03        (16 | (4 << 8))
#define MAP_NAVEL_ROCK_DOWN04        (17 | (4 << 8))
#define MAP_NAVEL_ROCK_DOWN05        (18 | (4 << 8))
#define MAP_NAVEL_ROCK_DOWN06        (19 | (4 << 8))
#define MAP_NAVEL_ROCK_DOWN07        (20 | (4 << 8))
#define MAP_NAVEL_ROCK_DOWN08        (21 | (4 << 8))
#define MAP_NAVEL_ROCK_DOWN09        (22 | (4 << 8))
#define MAP_NAVEL_ROCK_DOWN10        (23 | (4 << 8))
#define MAP_NAVEL_ROCK_DOWN11        (24 | (4 << 8))
#define MAP_NAVEL_ROCK_BOTTOM        (25 | (4 << 8))

// gMapGroup_IndoorDynamic
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (5 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (5 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (5 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (5 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (5 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (5 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (5 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (5 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (5 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (5 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (5 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (5 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (5 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (5 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (5 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (5 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (5 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (5 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (5 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (5 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (5 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (5 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (5 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (5 << 8))
#define MAP_BATTLE_COLOSSEUM_2P      (24 | (5 << 8))
#define MAP_TRADE_CENTER             (25 | (5 << 8))
#define MAP_RECORD_CORNER            (26 | (5 << 8))
#define MAP_BATTLE_COLOSSEUM_4P      (27 | (5 << 8))
#define MAP_CONTEST_HALL             (28 | (5 << 8))
#define MAP_UNUSED_CONTEST_HALL1     (29 | (5 << 8))
#define MAP_UNUSED_CONTEST_HALL2     (30 | (5 << 8))
#define MAP_UNUSED_CONTEST_HALL3     (31 | (5 << 8))
#define MAP_UNUSED_CONTEST_HALL4     (32 | (5 << 8))
#define MAP_UNUSED_CONTEST_HALL5     (33 | (5 << 8))
#define MAP_UNUSED_CONTEST_HALL6     (34 | (5 << 8))
#define MAP_CONTEST_HALL_BEAUTY      (35 | (5 << 8))
#define MAP_CONTEST_HALL_TOUGH       (36 | (5 << 8))
#define MAP_CONTEST_HALL_COOL        (37 | (5 << 8))
#define MAP_CONTEST_HALL_SMART       (38 | (5 << 8))
#define MAP_CONTEST_HALL_CUTE        (39 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01  (40 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02  (41 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03  (42 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04  (43 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05  (44 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06  (45 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07  (46 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08  (47 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09  (48 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10  (49 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11  (50 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12  (51 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13  (52 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14  (53 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15  (54 | (5 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16  (55 | (5 << 8))
#define MAP_UNION_ROOM               (56 | (5 << 8))

// gMapGroup_TownsAndRoutes
#define MAP_PALLET_TOWN             (0 | (6 << 8))
#define MAP_VIRIDIAN_CITY           (1 | (6 << 8))
#define MAP_PEWTER_CITY             (2 | (6 << 8))
#define MAP_CERULEAN_CITY           (3 | (6 << 8))
#define MAP_LAVENDER_TOWN           (4 | (6 << 8))
#define MAP_VERMILION_CITY          (5 | (6 << 8))
#define MAP_CELADON_CITY            (6 | (6 << 8))
#define MAP_FUCHSIA_CITY            (7 | (6 << 8))
#define MAP_CINNABAR_ISLAND         (8 | (6 << 8))
#define MAP_SAFFRON_CITY            (9 | (6 << 8))
#define MAP_ROUTE1                  (10 | (6 << 8))
#define MAP_ROUTE2                  (11 | (6 << 8))
#define MAP_ROUTE3                  (12 | (6 << 8))
#define MAP_ROUTE4                  (13 | (6 << 8))
#define MAP_ROUTE5                  (14 | (6 << 8))
#define MAP_ROUTE6                  (15 | (6 << 8))
#define MAP_ROUTE7                  (16 | (6 << 8))
#define MAP_ROUTE8                  (17 | (6 << 8))
#define MAP_ROUTE9                  (18 | (6 << 8))
#define MAP_ROUTE10                 (19 | (6 << 8))
#define MAP_ROUTE11                 (20 | (6 << 8))
#define MAP_ROUTE12                 (21 | (6 << 8))
#define MAP_ROUTE13                 (22 | (6 << 8))
#define MAP_ROUTE14                 (23 | (6 << 8))
#define MAP_ROUTE15                 (24 | (6 << 8))
#define MAP_ROUTE16                 (25 | (6 << 8))
#define MAP_ROUTE17                 (26 | (6 << 8))
#define MAP_ROUTE18                 (27 | (6 << 8))
#define MAP_ROUTE19                 (28 | (6 << 8))
#define MAP_ROUTE20                 (29 | (6 << 8))
#define MAP_ROUTE21_NORTH           (30 | (6 << 8))
#define MAP_ROUTE21_SOUTH           (31 | (6 << 8))
#define MAP_ROUTE22                 (32 | (6 << 8))
#define MAP_ROUTE23                 (33 | (6 << 8))
#define MAP_ROUTE24                 (34 | (6 << 8))
#define MAP_ROUTE25                 (35 | (6 << 8))
#define MAP_INDIGO_PLATEAU_EXTERIOR (36 | (6 << 8))
#define MAP_BATTLE_TOWER_EXTERIOR   (37 | (6 << 8))

// gMapGroup_Dungeons
#define MAP_VICTORY_ROAD_1F                     (0 | (7 << 8))
#define MAP_VICTORY_ROAD_2F                     (1 | (7 << 8))
#define MAP_VICTORY_ROAD_3F                     (2 | (7 << 8))
#define MAP_VIRIDIAN_FOREST                     (3 | (7 << 8))
#define MAP_MT_MOON_1F                          (4 | (7 << 8))
#define MAP_MT_MOON_B1F                         (5 | (7 << 8))
#define MAP_MT_MOON_B2F                         (6 | (7 << 8))
#define MAP_SSANNE_EXTERIOR                     (7 | (7 << 8))
#define MAP_SSANNE_1F_CORRIDOR                  (8 | (7 << 8))
#define MAP_SSANNE_2F_CORRIDOR                  (9 | (7 << 8))
#define MAP_SSANNE_3F_CORRIDOR                  (10 | (7 << 8))
#define MAP_SSANNE_B1F_CORRIDOR                 (11 | (7 << 8))
#define MAP_SSANNE_DECK                         (12 | (7 << 8))
#define MAP_SSANNE_KITCHEN                      (13 | (7 << 8))
#define MAP_SSANNE_CAPTAINS_OFFICE              (14 | (7 << 8))
#define MAP_SSANNE_1F_ROOM1                     (15 | (7 << 8))
#define MAP_SSANNE_1F_ROOM2                     (16 | (7 << 8))
#define MAP_SSANNE_1F_ROOM3                     (17 | (7 << 8))
#define MAP_SSANNE_1F_ROOM4                     (18 | (7 << 8))
#define MAP_SSANNE_1F_ROOM5                     (19 | (7 << 8))
#define MAP_SSANNE_1F_ROOM6                     (20 | (7 << 8))
#define MAP_SSANNE_1F_ROOM7                     (21 | (7 << 8))
#define MAP_SSANNE_2F_ROOM1                     (22 | (7 << 8))
#define MAP_SSANNE_2F_ROOM2                     (23 | (7 << 8))
#define MAP_SSANNE_2F_ROOM3                     (24 | (7 << 8))
#define MAP_SSANNE_2F_ROOM4                     (25 | (7 << 8))
#define MAP_SSANNE_2F_ROOM5                     (26 | (7 << 8))
#define MAP_SSANNE_2F_ROOM6                     (27 | (7 << 8))
#define MAP_SSANNE_B1F_ROOM1                    (28 | (7 << 8))
#define MAP_SSANNE_B1F_ROOM2                    (29 | (7 << 8))
#define MAP_SSANNE_B1F_ROOM3                    (30 | (7 << 8))
#define MAP_SSANNE_B1F_ROOM4                    (31 | (7 << 8))
#define MAP_SSANNE_B1F_ROOM5                    (32 | (7 << 8))
#define MAP_UNDERGROUND_PATH_NORTH_ENTRANCE     (33 | (7 << 8))
#define MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL (34 | (7 << 8))
#define MAP_UNDERGROUND_PATH_SOUTH_ENTRANCE     (35 | (7 << 8))
#define MAP_UNDERGROUND_PATH_WEST_ENTRANCE      (36 | (7 << 8))
#define MAP_UNDERGROUND_PATH_EAST_WEST_TUNNEL   (37 | (7 << 8))
#define MAP_UNDERGROUND_PATH_EAST_ENTRANCE      (38 | (7 << 8))
#define MAP_DIGLETTS_CAVE_NORTH_ENTRANCE        (39 | (7 << 8))
#define MAP_DIGLETTS_CAVE_B1F                   (40 | (7 << 8))
#define MAP_DIGLETTS_CAVE_SOUTH_ENTRANCE        (41 | (7 << 8))
#define MAP_ROCKET_HIDEOUT_B1F                  (42 | (7 << 8))
#define MAP_ROCKET_HIDEOUT_B2F                  (43 | (7 << 8))
#define MAP_ROCKET_HIDEOUT_B3F                  (44 | (7 << 8))
#define MAP_ROCKET_HIDEOUT_B4F                  (45 | (7 << 8))
#define MAP_ROCKET_HIDEOUT_ELEVATOR             (46 | (7 << 8))
#define MAP_SILPH_CO_1F                         (47 | (7 << 8))
#define MAP_SILPH_CO_2F                         (48 | (7 << 8))
#define MAP_SILPH_CO_3F                         (49 | (7 << 8))
#define MAP_SILPH_CO_4F                         (50 | (7 << 8))
#define MAP_SILPH_CO_5F                         (51 | (7 << 8))
#define MAP_SILPH_CO_6F                         (52 | (7 << 8))
#define MAP_SILPH_CO_7F                         (53 | (7 << 8))
#define MAP_SILPH_CO_8F                         (54 | (7 << 8))
#define MAP_SILPH_CO_9F                         (55 | (7 << 8))
#define MAP_SILPH_CO_10F                        (56 | (7 << 8))
#define MAP_SILPH_CO_11F                        (57 | (7 << 8))
#define MAP_SILPH_CO_ELEVATOR                   (58 | (7 << 8))
#define MAP_POKEMON_MANSION_1F                  (59 | (7 << 8))
#define MAP_POKEMON_MANSION_2F                  (60 | (7 << 8))
#define MAP_POKEMON_MANSION_3F                  (61 | (7 << 8))
#define MAP_POKEMON_MANSION_B1F                 (62 | (7 << 8))
#define MAP_POKEMON_TOWER_1F                    (63 | (7 << 8))
#define MAP_POKEMON_TOWER_2F                    (64 | (7 << 8))
#define MAP_POKEMON_TOWER_3F                    (65 | (7 << 8))
#define MAP_POKEMON_TOWER_4F                    (66 | (7 << 8))
#define MAP_POKEMON_TOWER_5F                    (67 | (7 << 8))
#define MAP_POKEMON_TOWER_6F                    (68 | (7 << 8))
#define MAP_POKEMON_TOWER_7F                    (69 | (7 << 8))
#define MAP_POWER_PLANT                         (70 | (7 << 8))
#define MAP_CERULEAN_CAVE_1F                    (71 | (7 << 8))
#define MAP_CERULEAN_CAVE_2F                    (72 | (7 << 8))
#define MAP_CERULEAN_CAVE_B1F                   (73 | (7 << 8))
#define MAP_ROCK_TUNNEL_1F                      (74 | (7 << 8))
#define MAP_ROCK_TUNNEL_B1F                     (75 | (7 << 8))
#define MAP_SEAFOAM_ISLANDS_1F                  (76 | (7 << 8))
#define MAP_SEAFOAM_ISLANDS_B1F                 (77 | (7 << 8))
#define MAP_SEAFOAM_ISLANDS_B2F                 (78 | (7 << 8))
#define MAP_SEAFOAM_ISLANDS_B3F                 (79 | (7 << 8))
#define MAP_SEAFOAM_ISLANDS_B4F                 (80 | (7 << 8))
#define MAP_VICTORY_ROAD_MOLTRES_CAVE           (81 | (7 << 8))

// gMapGroup_SpecialArea
#define MAP_SAFARI_ZONE_CENTER                              (0 | (8 << 8))
#define MAP_SAFARI_ZONE_EAST                                (1 | (8 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (2 | (8 << 8))
#define MAP_SAFARI_ZONE_WEST                                (3 | (8 << 8))
#define MAP_SAFARI_ZONE_CENTER_REST_HOUSE                   (4 | (8 << 8))
#define MAP_SAFARI_ZONE_EAST_REST_HOUSE                     (5 | (8 << 8))
#define MAP_SAFARI_ZONE_NORTH_REST_HOUSE                    (6 | (8 << 8))
#define MAP_SAFARI_ZONE_WEST_REST_HOUSE                     (7 | (8 << 8))
#define MAP_SAFARI_ZONE_SECRET_HOUSE                        (8 | (8 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (9 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (10 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (11 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (12 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (13 | (8 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (14 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (15 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (16 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (17 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (18 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (19 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (20 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (21 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (22 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (23 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (24 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (25 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (26 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (27 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (28 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (29 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (30 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (31 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (32 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (33 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (34 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (35 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (36 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (37 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (38 | (8 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (39 | (8 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (40 | (8 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (41 | (8 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (42 | (8 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (43 | (8 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (44 | (8 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (45 | (8 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (46 | (8 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (47 | (8 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (48 | (8 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (49 | (8 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (50 | (8 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (51 | (8 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (52 | (8 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (53 | (8 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (54 | (8 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (55 | (8 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (56 | (8 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (57 | (8 << 8))

// gMapGroup_IndoorPallet
#define MAP_PALLET_TOWN_PLAYERS_HOUSE_1F   (0 | (9 << 8))
#define MAP_PALLET_TOWN_PLAYERS_HOUSE_2F   (1 | (9 << 8))
#define MAP_PALLET_TOWN_RIVALS_HOUSE       (2 | (9 << 8))
#define MAP_PALLET_TOWN_PROFESSOR_OAKS_LAB (3 | (9 << 8))

// gMapGroup_IndoorViridian
#define MAP_VIRIDIAN_CITY_HOUSE             (0 | (10 << 8))
#define MAP_VIRIDIAN_CITY_GYM               (1 | (10 << 8))
#define MAP_VIRIDIAN_CITY_SCHOOL            (2 | (10 << 8))
#define MAP_VIRIDIAN_CITY_MART              (3 | (10 << 8))
#define MAP_VIRIDIAN_CITY_POKEMON_CENTER_1F (4 | (10 << 8))
#define MAP_VIRIDIAN_CITY_POKEMON_CENTER_2F (5 | (10 << 8))

// gMapGroup_IndoorPewter
#define MAP_PEWTER_CITY_MUSEUM_1F         (0 | (11 << 8))
#define MAP_PEWTER_CITY_MUSEUM_2F         (1 | (11 << 8))
#define MAP_PEWTER_CITY_GYM               (2 | (11 << 8))
#define MAP_PEWTER_CITY_MART              (3 | (11 << 8))
#define MAP_PEWTER_CITY_POKEMON_CENTER_1F (4 | (11 << 8))
#define MAP_PEWTER_CITY_POKEMON_CENTER_2F (5 | (11 << 8))
#define MAP_PEWTER_CITY_HOUSE1            (6 | (11 << 8))
#define MAP_PEWTER_CITY_HOUSE2            (7 | (11 << 8))

// gMapGroup_IndoorCerulean
#define MAP_CERULEAN_CITY_HOUSE1            (0 | (12 << 8))
#define MAP_CERULEAN_CITY_HOUSE2            (1 | (12 << 8))
#define MAP_CERULEAN_CITY_HOUSE3            (2 | (12 << 8))
#define MAP_CERULEAN_CITY_HOUSE4            (3 | (12 << 8))
#define MAP_CERULEAN_CITY_HOUSE5            (4 | (12 << 8))
#define MAP_CERULEAN_CITY_GYM               (5 | (12 << 8))
#define MAP_CERULEAN_CITY_BIKE_SHOP         (6 | (12 << 8))
#define MAP_CERULEAN_CITY_MART              (7 | (12 << 8))
#define MAP_CERULEAN_CITY_POKEMON_CENTER_1F (8 | (12 << 8))
#define MAP_CERULEAN_CITY_POKEMON_CENTER_2F (9 | (12 << 8))

// gMapGroup_IndoorLavender
#define MAP_LAVENDER_TOWN_POKEMON_CENTER_1F       (0 | (13 << 8))
#define MAP_LAVENDER_TOWN_POKEMON_CENTER_2F       (1 | (13 << 8))
#define MAP_LAVENDER_TOWN_MART                    (2 | (13 << 8))
#define MAP_LAVENDER_TOWN_VOLUNTEER_POKEMON_HOUSE (3 | (13 << 8))
#define MAP_LAVENDER_TOWN_HOUSE1                  (4 | (13 << 8))
#define MAP_LAVENDER_TOWN_HOUSE2                  (5 | (13 << 8))

// gMapGroup_IndoorVermilion
#define MAP_VERMILION_CITY_HOUSE1            (0 | (14 << 8))
#define MAP_VERMILION_CITY_HOUSE2            (1 | (14 << 8))
#define MAP_VERMILION_CITY_HOUSE3            (2 | (14 << 8))
#define MAP_VERMILION_CITY_POKEMON_CENTER_1F (3 | (14 << 8))
#define MAP_VERMILION_CITY_POKEMON_CENTER_2F (4 | (14 << 8))
#define MAP_VERMILION_CITY_MART              (5 | (14 << 8))
#define MAP_VERMILION_CITY_GYM               (6 | (14 << 8))
#define MAP_VERMILION_CITY_POKEMON_FAN_CLUB  (7 | (14 << 8))

// gMapGroup_IndoorCeladon
#define MAP_CELADON_CITY_POKEMON_CENTER_1F         (0 | (15 << 8))
#define MAP_CELADON_CITY_POKEMON_CENTER_2F         (1 | (15 << 8))
#define MAP_CELADON_CITY_GYM                       (2 | (15 << 8))
#define MAP_CELADON_CITY_RESTAURANT                (3 | (15 << 8))
#define MAP_CELADON_CITY_HOTEL                     (4 | (15 << 8))
#define MAP_CELADON_CITY_HOUSE1                    (5 | (15 << 8))
#define MAP_CELADON_CITY_GAME_CORNER               (6 | (15 << 8))
#define MAP_CELADON_CITY_GAME_CORNER_PRIZE_ROOM    (7 | (15 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_1F           (8 | (15 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_2F           (9 | (15 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_3F           (10 | (15 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_ROOF         (11 | (15 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_ROOF_ROOM    (12 | (15 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_1F       (13 | (15 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_2F       (14 | (15 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_3F       (15 | (15 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_4F       (16 | (15 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_5F       (17 | (15 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_ROOF     (18 | (15 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_ELEVATOR (19 | (15 << 8))

// gMapGroup_IndoorFuchsia
#define MAP_FUCHSIA_CITY_POKEMON_CENTER_1F    (0 | (16 << 8))
#define MAP_FUCHSIA_CITY_POKEMON_CENTER_2F    (1 | (16 << 8))
#define MAP_FUCHSIA_CITY_MART                 (2 | (16 << 8))
#define MAP_FUCHSIA_CITY_GYM                  (3 | (16 << 8))
#define MAP_FUCHSIA_CITY_HOUSE1               (4 | (16 << 8))
#define MAP_FUCHSIA_CITY_HOUSE2               (5 | (16 << 8))
#define MAP_FUCHSIA_CITY_HOUSE3               (6 | (16 << 8))
#define MAP_FUCHSIA_CITY_WARDENS_HOUSE        (7 | (16 << 8))
#define MAP_FUCHSIA_CITY_SAFARI_ZONE_OFFICE   (8 | (16 << 8))
#define MAP_FUCHSIA_CITY_SAFARI_ZONE_ENTRANCE (9 | (16 << 8))

// gMapGroup_IndoorCinnabar
#define MAP_CINNABAR_ISLAND_POKEMON_CENTER_1F   (0 | (17 << 8))
#define MAP_CINNABAR_ISLAND_POKEMON_CENTER_2F   (1 | (17 << 8))
#define MAP_CINNABAR_ISLAND_MART                (2 | (17 << 8))
#define MAP_CINNABAR_ISLAND_GYM                 (3 | (17 << 8))
#define MAP_CINNABAR_ISLAND_LAB_ENTRANCE        (4 | (17 << 8))
#define MAP_CINNABAR_ISLAND_LAB_LOUNGE          (5 | (17 << 8))
#define MAP_CINNABAR_ISLAND_LAB_RESEARCH_ROOM   (6 | (17 << 8))
#define MAP_CINNABAR_ISLAND_LAB_EXPERIMENT_ROOM (7 | (17 << 8))
#define MAP_CINNABAR_ISLAND_HOUSE               (8 | (17 << 8))

// gMapGroup_IndoorSaffron
#define MAP_SAFFRON_CITY_POKEMON_CENTER_1F        (0 | (18 << 8))
#define MAP_SAFFRON_CITY_POKEMON_CENTER_2F        (1 | (18 << 8))
#define MAP_SAFFRON_CITY_MART                     (2 | (18 << 8))
#define MAP_SAFFRON_CITY_GYM                      (3 | (18 << 8))
#define MAP_SAFFRON_CITY_DOJO                     (4 | (18 << 8))
#define MAP_SAFFRON_CITY_MR_PSYCHICS_HOUSE        (5 | (18 << 8))
#define MAP_SAFFRON_CITY_POKEMON_TRAINER_FAN_CLUB (6 | (18 << 8))
#define MAP_SAFFRON_CITY_COPYCATS_HOUSE_1F        (7 | (18 << 8))
#define MAP_SAFFRON_CITY_COPYCATS_HOUSE_2F        (8 | (18 << 8))
#define MAP_SAFFRON_CITY_HOUSE                    (9 | (18 << 8))

// gMapGroup_IndoorIndigoPlateau
#define MAP_INDIGO_PLATEAU_POKEMON_CENTER_1F (0 | (19 << 8))
#define MAP_INDIGO_PLATEAU_POKEMON_CENTER_2F (1 | (19 << 8))
#define MAP_POKEMON_LEAGUE_LORELEIS_ROOM     (2 | (19 << 8))
#define MAP_POKEMON_LEAGUE_BRUNOS_ROOM       (3 | (19 << 8))
#define MAP_POKEMON_LEAGUE_AGATHAS_ROOM      (4 | (19 << 8))
#define MAP_POKEMON_LEAGUE_LANCES_ROOM       (5 | (19 << 8))
#define MAP_POKEMON_LEAGUE_CHAMPIONS_ROOM    (6 | (19 << 8))
#define MAP_POKEMON_LEAGUE_HALL_OF_FAME      (7 | (19 << 8))
#define MAP_POKEMON_LEAGUE_CHALLENGER_ROOM   (8 | (19 << 8))
#define MAP_POKEMON_LEAGUE_SECRET_BATTLE     (9 | (19 << 8))

// gMapGroup_IndoorBattleTower
#define MAP_BATTLE_TOWER_ENTRANCE  (0 | (20 << 8))
#define MAP_BATTLE_TOWER_BASEMENT  (1 | (20 << 8))
#define MAP_BATTLE_TOWER_2F_SHOP   (2 | (20 << 8))
#define MAP_BATTLE_TOWER_3F_LOUNGE (3 | (20 << 8))
#define MAP_BATTLE_TOWER_ELEVATOR  (4 | (20 << 8))
#define MAP_BATTLE_TOWER_HOUSE     (5 | (20 << 8))

// gMapGroup_IndoorRoute2
#define MAP_VIRIDIAN_FOREST_NORTH_ENTRANCE (0 | (21 << 8))
#define MAP_VIRIDIAN_FOREST_SOUTH_ENTRANCE (1 | (21 << 8))
#define MAP_ROUTE2_HOUSE                   (2 | (21 << 8))
#define MAP_ROUTE2_EAST_BUILDING           (3 | (21 << 8))

// gMapGroup_IndoorRoute4
#define MAP_ROUTE4_POKEMON_CENTER_1F (0 | (22 << 8))
#define MAP_ROUTE4_POKEMON_CENTER_2F (1 | (22 << 8))

// gMapGroup_IndoorRoute5
#define MAP_ROUTE5_POKEMON_DAY_CARE (0 | (23 << 8))
#define MAP_ROUTE5_SOUTH_ENTRANCE   (1 | (23 << 8))

// gMapGroup_IndoorRoute6
#define MAP_ROUTE6_NORTH_ENTRANCE (0 | (24 << 8))

// gMapGroup_IndoorRoute7
#define MAP_ROUTE7_EAST_ENTRANCE (0 | (25 << 8))

// gMapGroup_IndoorRoute8
#define MAP_ROUTE8_WEST_ENTRANCE (0 | (26 << 8))

// gMapGroup_IndoorRoute10
#define MAP_ROUTE10_POKEMON_CENTER_1F (0 | (27 << 8))
#define MAP_ROUTE10_POKEMON_CENTER_2F (1 | (27 << 8))

// gMapGroup_IndoorRoute11
#define MAP_ROUTE11_EAST_ENTRANCE_1F (0 | (28 << 8))
#define MAP_ROUTE11_EAST_ENTRANCE_2F (1 | (28 << 8))

// gMapGroup_IndoorRoute12
#define MAP_ROUTE12_NORTH_ENTRANCE_1F (0 | (29 << 8))
#define MAP_ROUTE12_NORTH_ENTRANCE_2F (1 | (29 << 8))
#define MAP_ROUTE12_FISHING_HOUSE     (2 | (29 << 8))

// gMapGroup_IndoorRoute15
#define MAP_ROUTE15_WEST_ENTRANCE_1F (0 | (30 << 8))
#define MAP_ROUTE15_WEST_ENTRANCE_2F (1 | (30 << 8))

// gMapGroup_IndoorRoute16
#define MAP_ROUTE16_NORTH_ENTRANCE_1F (0 | (31 << 8))
#define MAP_ROUTE16_NORTH_ENTRANCE_2F (1 | (31 << 8))
#define MAP_ROUTE16_HOUSE             (2 | (31 << 8))

// gMapGroup_IndoorRoute18
#define MAP_ROUTE18_EAST_ENTRANCE_1F (0 | (32 << 8))
#define MAP_ROUTE18_EAST_ENTRANCE_2F (1 | (32 << 8))

// gMapGroup_IndoorRoute22
#define MAP_ROUTE22_NORTH_ENTRANCE (0 | (33 << 8))

// gMapGroup_IndoorRoute25
#define MAP_ROUTE25_SEA_COTTAGE (0 | (34 << 8))

#define MAP_GROUPS_COUNT 35

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
