CeruleanCave_2F_MapScripts::
	.byte 0

CeruleanCave_2F_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE, 1
	release
	end

CeruleanCave_2F_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL, 1
	release
	end

CeruleanCave_2F_EventScript_ItemPPUp::
	finditem ITEM_PP_UP, 1
	release
	end

CeruleanCave_2F_EventScript_TM87::
	finditem ITEM_TM87, 1
	release
	end

CeruleanCave_2F_EventScript_MewtowniteY::
	finditem ITEM_MEWTWONITE_Y, 1
	release
	end

CeruleanCave_2F_EventScript_MewtowniteX::
	finditem ITEM_MEWTWONITE_X, 1
	release
	end
